[package]
name = "poem-rest-api-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1"
poem-openapi = "5.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
poem-openapi = { version = "5.1", features = ["swagger-ui"] }
